### ISSUE TITLE
Bad error when no FlowMeters defined

### ISSUE THREAD

**Issue by jgarber** [saturnflyer/radiant-vapor-extension#1]
When you have use_regexp on, VaporFlow.catch_with_regexp starts out with result = nil and then sets it to self.send_to_radiant on the first FlowMeter that doesn't match. If there are zero FlowMeters, however, it remains nil and Rails Metal chokes (and it's very hard to trace down).

Sorry this doesn't come with a patch! (out of time today)  Should be as simple as making the first line in catch_with_regexp be result = self.send_to_radiant instead of nil.  Or return result || self.send_to_radiant for the last line in that method.

**Comment by saturnflyer** [comment]
fixed.
